version: '3.1'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: ./bd_data
        target: /var/lib/postgresql/data
