version: '3.1'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 567234
      POSTGRES_DB: mydb
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: ./bd_data
        target: /var/lib/postgresql/data
